import { useMutation, useQuery } from "@tanstack/react-query";
import { FormEvent, useEffect, useState } from "react";
import { Link, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { api } from "./api/client";
import type { AcceptanceCriterion, Analysis, DecisionStatus, Finding, Rule, RunEvent, ValidationResult } from "./api/contract";

function Header() { return <header><Link to="/" className="wordmark">PR/QA <b>GATE</b></Link><nav><Link to="/">Nuevo análisis</Link><Link to="/analyses">Historial</Link><span>solo lectura</span></nav></header>; }
function Decision({ status }: { status: DecisionStatus }) { return <span className={`decision ${status.toLowerCase()}`}>{status}</span>; }
function ErrorMessage({ error }: { error: unknown }) { return <p role="alert" className="error">{error instanceof Error ? error.message : "No fue posible completar la solicitud."}</p>; }

function NewAnalysis() {
  const navigate = useNavigate(); const [url, setUrl] = useState(""); const [criteria, setCriteria] = useState<AcceptanceCriterion[]>([]);
  const models = useQuery({ queryKey: ["models"], queryFn: api.models }); const profiles = useQuery({ queryKey: ["validation-profiles"], queryFn: api.validationProfiles });
  const [modelId, setModelId] = useState(""); const [profileId, setProfileId] = useState("");
  useEffect(() => { if (!modelId && models.data?.models[0]) setModelId(models.data.models[0].id); }, [models.data, modelId]);
  useEffect(() => { if (!profileId && profiles.data?.validation_profiles[0]) setProfileId(profiles.data.validation_profiles[0].id); }, [profiles.data, profileId]);
  const create = useMutation({ mutationFn: () => api.createAnalysis({ pull_request_url: url, model_profile_id: modelId, validation_profile_id: profileId, acceptance_criteria: criteria }), onSuccess: ({ analysis_id }) => navigate(`/analyses/${analysis_id}`) });
  const submit = (event: FormEvent) => { event.preventDefault(); if (!modelId || !profileId) return; create.mutate(); };
  const addCriterion = () => setCriteria([...criteria, { id: `AC-${criteria.length + 1}`, text: "", required: true }]);
  const updateCriterion = (index: number, patch: Partial<AcceptanceCriterion>) => setCriteria(criteria.map((item, current) => current === index ? { ...item, ...patch } : item));
  return <main className="landing"><p className="eyebrow">PR → QA / evidence first</p><h1>Decidir con pruebas,<br /><i>no con intuición.</i></h1><p className="lede">Analiza un pull request de GitHub, valida una corrección en aislamiento y aplica una política trazable.</p><form onSubmit={submit}><label htmlFor="pr-url">URL del pull request</label><input id="pr-url" type="url" required placeholder="https://github.com/owner/repo/pull/42" value={url} onChange={(event) => setUrl(event.target.value)} />
    <div className="select-grid"><label>Modelo<select aria-label="Modelo" value={modelId} onChange={(event) => setModelId(event.target.value)}>{models.data?.models.map((item) => <option key={item.id} value={item.id}>{item.id} · {item.model}</option>)}</select></label><label>Perfil de validación<select aria-label="Perfil de validación" value={profileId} onChange={(event) => setProfileId(event.target.value)}>{profiles.data?.validation_profiles.map((item) => <option key={item.id} value={item.id}>{item.id}</option>)}</select></label></div>
    <div className="criteria"><div><label>Criterios de aceptación</label><button type="button" className="secondary" onClick={addCriterion}>Añadir criterio</button></div>{criteria.map((item, index) => <div className="criterion" key={index}><input aria-label={`Criterio ${index + 1}`} placeholder="Comportamiento verificable" value={item.text} required onChange={(event) => updateCriterion(index, { text: event.target.value })} /><label><input type="checkbox" checked={item.required} onChange={(event) => updateCriterion(index, { required: event.target.checked })} /> Obligatorio</label><button type="button" className="secondary" onClick={() => setCriteria(criteria.filter((_, current) => current !== index))}>Quitar</button></div>)}</div>
    <button disabled={create.isPending || models.isPending || profiles.isPending}>{create.isPending ? "Iniciando..." : "Analizar PR"}</button>{create.isError && <ErrorMessage error={create.error} />}</form><aside><b>Alcance controlado</b><span>GitHub read-only · comandos administrados · sin secretos en el navegador</span></aside></main>;
}

function useProgress(id: string, status: DecisionStatus | undefined) {
  const [events, setEvents] = useState<RunEvent[]>([]); const [sseFailed, setSseFailed] = useState(false); const [reconnects, setReconnects] = useState(0);
  const fallback = useQuery({ queryKey: ["events", id], queryFn: () => api.events(id), enabled: status === "PENDING" || status === "RUNNING", refetchInterval: sseFailed ? 1500 : false });
  useEffect(() => { if ((status !== "PENDING" && status !== "RUNNING") || sseFailed) return; const source = new EventSource(`/api/v1/analyses/${id}/stream`); source.addEventListener("progress", (event) => { const item = JSON.parse((event as MessageEvent).data) as RunEvent; setEvents((current) => current.some((value) => value.sequence === item.sequence) ? current : [...current, item]); }); source.onerror = () => { source.close(); if (reconnects >= 1) setSseFailed(true); else setReconnects((current) => current + 1); }; return () => source.close(); }, [id, status, sseFailed, reconnects]);
  return sseFailed ? fallback.data?.items ?? [] : events;
}

function FindingCard({ finding }: { finding: Finding }) { return <article className="finding"><div><b>{finding.severity}</b><span>{finding.category}</span></div><h3>{finding.title}</h3><p><code>{finding.file_path}:{finding.start_line}-{finding.end_line}</code></p><p>{finding.explanation}</p><blockquote>{finding.evidence_excerpt}</blockquote><p><b>Impacto:</b> {finding.impact}</p><p><b>Acción:</b> {finding.recommended_action}</p></article>; }
function Patch({ title, value }: { title: string; value?: string }) { return value ? <section><h2>{title}</h2><pre className="evidence">{value}</pre></section> : null; }
function RuleList({ rules }: { rules: Rule[] }) { return <div className="rules">{rules.map((rule) => <div className="rule" key={rule.id}><span>{rule.id}</span><b className={rule.outcome.toLowerCase()}>{rule.outcome}</b><p>{rule.message}{rule.evidence_ids?.length ? <small>Evidencia: {rule.evidence_ids.join(", ")}</small> : null}</p></div>)}</div>; }
function ValidationCard({ label, result }: { label: string; result?: ValidationResult }) { return <div><h3>{label}</h3>{result ? <dl className="validation"><dt>Comando</dt><dd>{result.command_name ?? "administrado"}</dd><dt>Exit code</dt><dd>{result.exit_code ?? "sin ejecutar"}</dd><dt>Estado</dt><dd>{result.infrastructure_error ? "Error de infraestructura" : result.timed_out ? "Timeout" : result.exit_code === 0 ? "Aprobado" : "Falló"}</dd>{result.stdout ? <><dt>Salida</dt><dd><pre>{result.stdout}</pre></dd></> : null}{result.stderr ? <><dt>Error</dt><dd><pre>{result.stderr}</pre></dd></> : null}</dl> : <p>Sin resultado disponible.</p>}</div>; }
function Evidence({ label, value }: { label: string; value: unknown }) { return <div><h3>{label}</h3><pre className="evidence">{value ? JSON.stringify(value, null, 2) : "Sin resultado disponible."}</pre></div>; }
function decisionHeading(status: DecisionStatus | undefined) { if (status === "BLOCKED") return "Cambio bloqueado"; if (status === "INCONCLUSIVE") return "Evidencia insuficiente"; if (status === "CONDITIONAL") return "Avance condicionado"; return "Decisión para QA"; }
function ReportBody({ analysis }: { analysis: Analysis }) {
  const report = analysis.report; const decision = report.decision; const findings = report.findings?.findings ?? []; const validation = report.validations; const pr = report.pull_request; const execution = report.execution; const llmNotExecuted = execution?.llm?.status === "NOT_EXECUTED";
  const tokenLabel = llmNotExecuted ? "No aplicable" : `${analysis.input_tokens ?? "no disponible"}/${analysis.output_tokens ?? "no disponible"}`;
  const costLabel = llmNotExecuted ? "No aplicable" : analysis.estimated_cost ?? "no disponible";
  return <main className="report"><p className="eyebrow">ANÁLISIS / {analysis.id.slice(0, 8)}</p><section className="decision-panel"><Decision status={decision?.status ?? analysis.status}/><div><h1>{decisionHeading(decision?.status)}</h1><p>{decision?.summary ?? analysis.error ?? "Esperando evidencia del workflow."}</p></div></section>
    <section><h2>Resumen del PR</h2>{pr?.url ? <dl className="metadata"><dt>PR</dt><dd><a href={pr.url} target="_blank" rel="noreferrer">{pr.url}</a></dd><dt>Título</dt><dd>{pr.title || "Sin título"}</dd><dt>SHA base</dt><dd><code>{pr.base_sha ?? "no disponible"}</code></dd><dt>SHA analizado</dt><dd><code>{pr.head_sha ?? report.head_sha ?? "no disponible"}</code></dd><dt>Estado</dt><dd>{pr.draft ? "Draft" : "Abierto"}</dd><dt>Archivos</dt><dd>{pr.modified_files.length ? pr.modified_files.join(", ") : "Sin archivos disponibles"}</dd></dl> : <p>La trazabilidad del PR no está disponible para este análisis histórico.</p>}</section>
    <section><h2>Hallazgos</h2>{findings.length ? findings.map((finding, index) => <FindingCard finding={finding} key={`${finding.file_path}-${index}`} />) : <p>Sin hallazgos confirmados por LLM.</p>}</section>
    {report.secret_evidence?.length ? <section><h2>Secretos detectados</h2><div className="rules">{report.secret_evidence.map((item) => <div className="rule" key={`${item.path}-${item.start_line}`}><span>GATE-006</span><b className="fail">FAIL</b><p><code>{item.path}:{item.start_line}-{item.end_line}</code><small>Patrón: {item.kinds.join(", ") || "secreto potencial"}. El valor fue redactado.</small></p></div>)}</div></section> : null}
    <Patch title="Corrección propuesta" value={report.fix?.patch}/><Patch title="Test de regresión" value={report.fix?.regression_test_patch}/>
    <section><h2>Validación del PR actual</h2><div className="comparison"><ValidationCard label="Suite" result={validation?.original?.results?.[0]}/><ValidationCard label="Lint" result={validation?.original?.results?.[1]}/></div></section><section><h2>Validación de la corrección propuesta</h2><p className="note">Estado: {validation?.candidate?.status ?? "No propuesta"}</p><div className="comparison"><ValidationCard label="Regresión antes" result={validation?.baseline?.result}/><ValidationCard label="Candidate" result={validation?.candidate?.results?.[0]}/></div></section><section><h2>Evidencia antes / después</h2><div className="comparison"><Evidence label="PR actual" value={validation?.original?.results}/><Evidence label="Candidate" value={validation?.candidate?.results}/></div></section>
    <section><h2>Criterios de aceptación</h2>{report.acceptance_criteria?.length ? <div className="rules">{report.acceptance_criteria.map((item) => <div className="rule" key={item.id}><span>{item.id}</span><b className={item.status.toLowerCase()}>{item.status}</b><p>{item.text}{item.evidence.length ? <small>Evidencia: {item.evidence.join(", ")}</small> : null}{item.reason ? <small>{item.reason}</small> : null}</p></div>)}</div> : <p>No se registraron criterios.</p>}</section>
    <section><h2>Política aplicada</h2>{decision?.rules ? <RuleList rules={decision.rules} /> : <p>No hay controles disponibles todavía.</p>}</section>
    <section><h2>Acciones necesarias</h2>{decision?.required_actions?.length ? <ol className="actions">{decision.required_actions.map((item) => <li key={item}>{item}</li>)}</ol> : <p>Sin acciones pendientes según la política.</p>}</section>
    <section><h2>Controles no ejecutados</h2>{execution?.not_executed_controls?.length ? <div className="rules">{execution.not_executed_controls.map((item) => <div className="rule" key={item.id}><span>{item.id}</span><b className="unknown">NO EJECUTADO</b><p>{item.label}<small>{item.reason}</small></p></div>)}</div> : <p>Todos los controles requeridos tuvieron una ejecución registrada.</p>}</section>
    <section><h2>Métricas</h2><p className="note">Modelo: {analysis.model_profile_id} · Duración: {analysis.duration_ms ?? "pendiente"} ms · Tokens: {tokenLabel} · Costo: {costLabel} · Política: {decision?.policy_version ?? "pendiente"}</p>{llmNotExecuted && execution?.llm?.reason ? <p className="note">LLM no ejecutado: {execution.llm.reason}</p> : null}</section><section><h2>Limitaciones</h2>{report.errors?.length ? report.errors.map((item) => <p className="note" key={item.code}>{item.message}</p>) : <p className="note">{analysis.error ?? "Sin limitaciones registradas."}</p>}</section></main>;
}
function AnalysisPage() { const { id = "" } = useParams(); const navigate = useNavigate(); const query = useQuery({ queryKey: ["analysis", id], queryFn: () => api.analysis(id), refetchInterval: (query) => ["PENDING", "RUNNING"].includes(query.state.data?.status ?? "") ? 1500 : false }); const events = useProgress(id, query.data?.status); useEffect(() => { if (query.data?.finished_at) navigate(`/analyses/${id}?report=1`, { replace: true }); }, [id, navigate, query.data?.finished_at]); if (query.isPending) return <main className="report"><p>Recuperando informe...</p></main>; if (query.isError) return <main className="report"><ErrorMessage error={query.error}/></main>; if (["PENDING", "RUNNING"].includes(query.data.status)) return <main className="report"><p className="eyebrow">ANÁLISIS EN PROGRESO</p><h1>Construyendo evidencia</h1><ol className="progress">{events.length ? events.map((item) => <li key={item.sequence}><b>{item.node}</b><span>{item.message}</span></li>) : <li>Conectando al workflow…</li>}</ol></main>; return <ReportBody analysis={query.data} />; }
function History() { const [filter, setFilter] = useState(""); const query = useQuery({ queryKey: ["analyses", filter], queryFn: () => api.history(filter || undefined) }); return <main className="report"><p className="eyebrow">REGISTRO PERSISTENTE</p><h1>Historial de análisis</h1><label>Filtrar por decisión<select aria-label="Filtrar por decisión" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="">Todas</option><option>READY</option><option>BLOCKED</option><option>INCONCLUSIVE</option><option>CONDITIONAL</option></select></label><section className="history">{query.isPending ? <p>Cargando...</p> : query.data?.items.length ? query.data.items.map((item) => <Link key={item.id} to={`/analyses/${item.id}`}><Decision status={item.status}/><span>{item.pull_request_url}<small>{item.model_profile_id} · {item.head_sha?.slice(0, 8) ?? "SHA pendiente"}</small></span><time>{new Date(item.created_at).toLocaleString()}</time></Link>) : <p>Aún no hay análisis para este filtro.</p>}</section></main>; }
export function App() { return <><Header/><Routes><Route path="/" element={<NewAnalysis/>}/><Route path="/analyses" element={<History/>}/><Route path="/analyses/:id" element={<AnalysisPage/>}/></Routes></>; }
